### ISSUE TITLE
Offset Data source

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#2]
I am maintain a similar database for SCOR but with significantly less ambitions. A good source of offset data it the WPP2019 that can be found very convenient in the `{wpp2019}` package. See `popM` and `popF` to get 5y-age data.

I am using the last available `HMD` exposures and deaths when I what to determine the excess in mortality during the covid epidemic.

**Comment by timriffe** [comment]
Thanks Marius, at the moment we're provisionally using the latest HMD data as offsets where applicable, and hunting down other offsets where required. For China we've used WPP2019 data, from the website, though, to get a 2020 estimate rather than a mid-interval estimate. For other places (NYC, Washington state, Taiwan) we use official 2020 projections. And we have many offsets yet to track down, but we'll get them. Filipe Ribeiro will work to harmonize offsets to the year 2020 (either Jan 1 or July 1, we're not going to nit pick as it's just instrumental for splitting the binned counts.).

Presently lacking offsets is the main reason why some inputs don't make it from the input database to the output database, but they'll get there soon enough. Happy to share info any time.

**Comment by mpascariu** [comment]
For the US states the US Census data seems to be fine:
https://data.census.gov/cedsci/table?table=DP05&tid=ACSDP1Y2017.DP05&lastDisplayedRow=29&vintage=2017&layer=state&cid=DP05_0001E&hidePreview=true&g=0400000US36&moe=false

Not sure if there is a fast way to read it in R.

**Comment by timriffe** [comment]
This looks promising, haven't given it a whirl yet:
https://cran.r-project.org/web/packages/tidycensus/tidycensus.pdf

**Comment by timriffe** [comment]
I found single age population estimates for US states with a reference date of July 1, 2018 [https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-detail.html](https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-detail.html), so pretty close. Sometime this year they will release 2020 estimates (it's a census year after all), so these can be replaced moving forward. Until then we will translate (not project) these to a 2020 reference date (which date tbd) using a simple method.
