### ISSUE TITLE
Brazil

### ISSUE THREAD

**Issue by vzarulli** [timriffe/covid_age#23]
![Brazil_deaths](https://user-images.githubusercontent.com/65513286/82708155-e1b80500-9c7d-11ea-8a45-965bc9652929.png)
Brazil deaths data have huge oscillations, especially for females. 
![Brazil_sr_deaths](https://user-images.githubusercontent.com/65513286/82708271-204dbf80-9c7e-11ea-8096-79098f3dadde.png)
Sex ratio (m/f) of the deaths from age 45 onwards has a sudden drop after the first few days.

**Comment by timriffe** [comment]
For the first figure, some of this will be due to the 1d PCLM, as you mention. To find any that are not due to pclm, just do the same thing on output in 10-year age groups. The Brazil data is collected in 10 year age groups, so any fluctuations there should be data artifacts.

For the second figure, that early drop is probably due to small counts in the early days. I replicated the calcs for that one using both input data and output data, a it did not produce fluctuations as large as those you're showing here. Just to be sure, Brazil has a separate Rio de Janeiro series, which has a more erratic sr in the early days. Just to be sure, these series aren't being mixed here, right?

**Comment by vzarulli** [comment]
Thank you. The series were mixed indeed. Looking at them separately everything seems alright. 
Also, with 10 years age groups Brazil looks better.

**Comment by vzarulli** [comment]
Hi Tim,
Last weekend I looked at about half of the countries and now that I’m taking into account also the regions they all looked quite fine except for the age 100+. In that case, deaths and
Cases are often either decreasing at some point or somehow bouncy. It is not the case in all the countries but very often yes..
As soon as I can check the other half of the countries, I can tell you the exact cases, but maybe it is only due to the fact that the 100+ category is simply problematic by itself?

Best,
Virginia
