### ISSUE TITLE
zip files

### ISSUE THREAD

**Issue by timriffe** [timriffe/covid_age#32]
`inputDB.csv`, `Output_5.csv` and `Output_10.csv` should all be zipped prior to OSF upload, ASAP.
then it works just the same `readr::read_csv("inputDB.zip")`

**Comment by timriffe** [comment]
done!

**Comment by liuyanguu** [comment]
As I am working on a dashboard that will load the output every day, I am wondering if there are other ways to read the data from OSF besides downloading the zip file using `osfr::osf_download` and then read using `readr`. It is still a little bit slow since it has to be unzipped (and it is indeed a large dataset). Any thought is welcome.

**Comment by timriffe** [comment]
Hi! No need to unzip those files in order to read with `read_csv()`. But now you have an alternative: There's a new `R` package, which we'll soon adjust our getting started guide to feature: 
`https://github.com/eshom/covid-age-data`
This package wraps the `osfr` part under the hood so you don't have to mess with it. There is also a function for out-of-memory reading of subsets into `R`. So for example you might filter on `Region = "All"`. Go ahead and give that package a spin, and stay tuned for the new getting started guide that uses it.

**Comment by liuyanguu** [comment]
This is very helpful! Neat package. Thank you.
