### ISSUE TITLE
Spanish Data

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#5]
I did a comparison between the Spanish data I collected and what I see in the `inputDB.csv` . 
The sources appear to be the same however at certain points in time consistent differences across multiple ages can be observed. E.g.: March 29, 31 and April 13.

This is related to #4.

Also, it is not clear to me what is reported when `Age == UNK`. Maybe unknown? For Spain very large numbers can be seen there.

See the file attached here:
[ESP_Data_Comparison_20200413.xlsx](https://github.com/timriffe/covid_age/files/4496106/ESP_Data_Comparison_20200413.xlsx)

**Comment by timriffe** [comment]
This will be cleared up over the course of this week. Previously we did an indirect calculation in the input spreadsheet to infer cases and deaths of unknown age. From table 1 we took the total cases and deaths. UNK was calculated as the difference between the table 1 total and the marginal sum from table 2. To get UNK for the sexes we took the observed sex ratio as valid for the total. If one doesn't do this step then the age-specific case fatality rates in Spain are vastly underestimated. This is because ca 60% of cases but only ca 40% of deaths have had a reported age. Make sense? However, we were inconsistent about this. The Spain database will now be sanitized in the following way: We will remove All UNK lines and capture both-sex total cases and deaths for each day in the series. We will then do all rescaling in R, so that it's consistent. For those subsets where we had UNK calculations so far, the result will be the same, however for those where we failed to do the UNK calc it will now be amended.
